spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=headlyboi
spring.datasource.password=headlyboi
spring.datasource.url=jdbc:postgresql://localhost:5432/headlyboi

discord.bot.token=
discord.channel.name=stats-finder

tracker.gg.token=
url.tracker.gg.player.data=https://api.mozambiquehe.re/bridge?auth=%s&player=%s&platform=%s

